version: '3'

volumes:
  db-data: {}
  redisdata: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    restart: always
    environment: #django settings.py conifg
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=djangodocker_db
      - DJANGO_DB_USERNAME=root
      - DJANGO_DB_PASSWORD=root
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./:/code/
    #command: gunicorn hanium.wsgi:application --bind 0.0.0.0:8000
    #command: bin/run.sh
    command: bash -c "python manage.py makemigrations main chat && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    #command: bash -c "python manage.py migrate && gunicorn hanium.wsgi -b 0.0.0.0:8000"
    links:
      - db
      - redis
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=djangodocker_db
      - TZ=Asia/Seoul
    volumes:
      - db-data:/var/lib/mysql
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./compose/nginx:/etc/nginx/conf.d
    depends_on:
      - django
  redis:
    image: redis
    expose:
      - "6379"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redisdata:/data
